### ISSUE TITLE
GNU Stow repo compatibility

### ISSUE THREAD

**Issue by punassuming** [ralish/PSDotFiles#4]
Just came across this.  Was looking for dfm system that would allow me to use a central REPO across windows (PS primarily) and WSL / linux builds.  I have read a bit about Stow, but was wondering the level of compatibility between this repo and Stow in terms of setting up the dotfiles repo.

**Comment by ralish** [comment]
Extremely belated reply, but to answer your question, combining PSDotFiles with Stow for cross-platform support is entirely possible. In fact, I do exactly this in my own [dotfiles](https://github.com/ralish/dotfiles) repository.

My general experience is applications that are cross-platform use the same configuration files and directory structure across operating systems, but have a potentially different base storage location. So for example, an application might store its configuration files in `$HOME` on Linux but `%AppData%` on Windows. However, under those locations, the actual files/folders are the same.

PSDotFiles is very amenable to this as it's designed to be flexible as to the target location for any given component (a set of files corresponding to a given application, utility, etc...). I'd suggest taking a look at my own dotfiles as sample material. Particularly important are the the XML files in the `metadata` folder which instruct PSDotFiles on how to handle each component where non-default behaviour is necessary.
